
python-3.5:
  image: python:3.5
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tox
    - pip3 install pytest-cov
    - tox -e py35
    - pytest --cov=proclamation

python-3.6:
  image: python:3.6
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tox
    - pip3 install pytest-cov
    - tox -e py36
    - pytest --cov=proclamation

python-3.7:
  image: python:3.7
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tox
    - pip3 install pytest-cov
    - tox -e py37
    - pytest --cov=proclamation


flake8:
  image: python:3.7
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tox
    - tox -e flake8
