
python-3.4:
  image: python:3.4
  script:
    - tox -e py34

python-3.5:
  image: python:3.5
  script:
    - tox -e py35

python-3.6:
  image: python:3.6
  script:
    - tox -e py36

python-3.7:
  image: python:3.7
  script:
    - tox -e py37


flake8:
  image: python:3.7
  script:
    - tox -e flake8
